name: Bonjour
on:
  - push
  - pull_request
jobs:
  ci:
    runs-on: ubuntu-22.04
    
    steps:
      - uses: actions/checkout@v4  
      
      - uses: actions/setup-node@v4
        with:
          name : Setup Node
          node-version: 20.17.0
      - run: npm ci
      - run: node --version
      - run: npm run build && node dist/index.js 
      - run: ls dist/
      

      
      
      

