name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: ls -l # Liste les fichier du répertoire courant
      - run: sudo apt install cowsay
      
      - run: cat README.md | cowsay
      

