name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: ls -l # Liste les fichier du répertoire courant
      - run: sudo apt install cowsay
      - run: sudo apt install sl
      - run: cat README.md | cowsay
      - run: for i in a l f o
             do
                sl -${i} | lolcat
             done
      

